### PR TITLE
chore: add tests script, simplify github actions

### PR DESCRIPTION
**Pull request by bshaffer**
Simplifies our github workflow file by adding a global `tests.sh` script which handles skipping tests (when credentials are absent) and finding all possible wrappers to run.

### CODE REVIEW

**Comment by jamesward** [comment]
Nice!

**Review by jamesward — APPROVED** [review]

**Comment by jamesward** [comment]
Looks like the tests failed because `tests.sh` wasn't executable or something.

**Comment by jamesward** [comment]
Couple projects failing tests. That ok?

**Comment by bshaffer** [comment]
@jamesward I'm working on them! Should be an easy fix - I updated loads of dependencies yesterday and because they were on forks the tests didn't run until now :-/

**Pull request merged**
